services:
  mouse_control:
    container_name: kilted
    build: .
    volumes:
      - .:/work
    environment:
      - DISPLAY=${DISPLAY:-host.docker.internal:0.0}
      - POSTGRES_HOST=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    tty: true
    stdin_open: true
    restart: unless-stopped

  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
   
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecretPassword
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge